name: 'Cloudfoundry Action'
description: 'Github action to deploy to cloudfoundry'
author: 'Comsysto Reply'
 inputs:
   myInput:
     description: 'Input to use'
     default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
   args:
     - ${{ inputs.myInput }}
