name: 'Cloudfoundry Action'
description: 'Github action to authenticate to cloudfoundry'
author: 'Comsysto Reply'
inputs:
  api:
    description: 'The cloudfoundry api to connect to'
  user:
    description: 'The username used to login to cloudfoundry'
  password:
    description: 'The password used to login to cloudfoundry'
outputs:
  authResult:
    description: 'The result of the cf authentication'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
